### ISSUE TITLE
CAPA crashing with nil pointer

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-aws#1190]
/kind bug

```
I1010 01:27:37.882941       1 instances.go:104] controllers/AWSMachine "msg"="Creating an instance for a machine" "awsCluster"="yang-oct9-dev5" "awsMachine"="worker-yang-oct9-dev5-default-node-pool-zd4wm" "cluster"="yang-oct9-dev5" "machine"="worker-yang-oct9-dev5-default-node-pool-ccbbc89d4-cl9dz" "namespace"="bda5dcdbc1b5daf72ddd139676ff4687ed2d849a" 
E1010 01:27:37.883134       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 287 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1855b60, 0x2def390)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x82
panic(0x1855b60, 0x2def390)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/ec2.(*Service).CreateInstance(0xc00000f7f8, 0xc000b22b40, 0xc00000f7f8, 0x0, 0x0)
	/workspace/pkg/cloud/services/ec2/instances.go:131 +0x1618
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).getOrCreate(0xc000657980, 0xc000b22b40, 0xc00000f7f8, 0x1adfd83, 0x2a, 0x1)
	/workspace/controllers/awsmachine_controller.go:344 +0x8f
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).reconcileNormal(0xc000657980, 0x1ddba60, 0xc000056070, 0xc000b22b40, 0xc000407f80, 0x0, 0x1dfa320, 0xc0005bbe90, 0x1dec940)
	/workspace/controllers/awsmachine_controller.go:273 +0x1c0
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).Reconcile(0xc000657980, 0xc000438f60, 0x28, 0xc000438f30, 0x2d, 0x2e07f00, 0x0, 0x0, 0x0)
	/workspace/controllers/awsmachine_controller.go:144 +0xa62
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000237400, 0x18d8ce0, 0xc00025f240, 0x18d8c00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:216 +0x146
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000237400, 0xc0006e7700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192 +0xb5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000237400)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a1f80)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a1f80, 0x3b9aca00, 0x0, 0x1, 0xc0001c7440)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006a1f80, 0x3b9aca00, 0xc0001c7440)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:157 +0x311
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14882f8]

goroutine 287 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1855b60, 0x2def390)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/ec2.(*Service).CreateInstance(0xc00000f7f8, 0xc000b22b40, 0xc00000f7f8, 0x0, 0x0)
	/workspace/pkg/cloud/services/ec2/instances.go:131 +0x1618
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).getOrCreate(0xc000657980, 0xc000b22b40, 0xc00000f7f8, 0x1adfd83, 0x2a, 0x1)
	/workspace/controllers/awsmachine_controller.go:344 +0x8f
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).reconcileNormal(0xc000657980, 0x1ddba60, 0xc000056070, 0xc000b22b40, 0xc000407f80, 0x0, 0x1dfa320, 0xc0005bbe90, 0x1dec940)
	/workspace/controllers/awsmachine_controller.go:273 +0x1c0
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSMachineReconciler).Reconcile(0xc000657980, 0xc000438f60, 0x28, 0xc000438f30, 0x2d, 0x2e07f00, 0x0, 0x0, 0x0)
	/workspace/controllers/awsmachine_controller.go:144 +0xa62
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000237400, 0x18d8ce0, 0xc00025f240, 0x18d8c00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:216 +0x146
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000237400, 0xc0006e7700)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:192 +0xb5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000237400)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:171 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0006a1f80)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0006a1f80, 0x3b9aca00, 0x0, 0x1, 0xc0001c7440)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0006a1f80, 0x3b9aca00, 0xc0001c7440)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.2/pkg/internal/controller/controller.go:157 +0x311

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version:  staging latest image

**Comment by vincepri** [comment]
The line suggest the Machine is missing the Kubernetes version field 

/priority awaiting-more-evidence

**Comment by Lokicity** [comment]
@vincepri  Yea that is likely. Should CAPA ever throw nil pointer? Maybe there could be a fix on CAPA side to catch `missing version field` . Let me check on my side

**Comment by tahsinrahman** [comment]
similar to this? https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1092

**Comment by ncdc** [comment]
Yes, this is probably a duplicate

**Comment by ncdc** [comment]
@Lokicity can you confirm you didn't have the version field set?

**Comment by Lokicity** [comment]
Yes, I can confirm I dont have the version field set. Close it due to duplicate bug: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1092
