### ISSUE TITLE
Panic in getAPIServerClassicELBSpec

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-aws#1520]
**What steps did you take and what happened:**
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-master/1224459024594898945 is failing because the capa pod is panicking.

https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-master/1224459024594898945/artifacts/logs/capa-controller-manager/capa-controller-manager-768c8cb9fc-q84m7/manager.log
```
I0203 22:36:15.737872       1 natgateways.go:204] controllers/AWSCluster "msg"="NAT gateway for subnet is now available" "awsCluster"="test-infra-raprut" "cluster"="test-r8aqur" "namespace"="test-mdki87" "nat-gateway-id"="nat-019f36ec6ee880bf5" "subnet-id"="subnet-09161da1a552ebed5"
E0203 22:36:19.246107       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 268 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x18cf500, 0x2c2d910)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/runtime/runtime.go:48 +0x82
panic(0x18cf500, 0x2c2d910)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).getAPIServerClassicELBSpec(0xc0006678e0, 0x1b5710d, 0x1a, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:271 +0x43b
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/elb.(*Service).ReconcileLoadbalancers(0xc0006678e0, 0x0, 0x0)
	/workspace/pkg/cloud/services/elb/loadbalancer.go:47 +0xa2
sigs.k8s.io/cluster-api-provider-aws/controllers.reconcileNormal(0xc0002e6ee0, 0xc000154648, 0x1ef01a0, 0xc000154658, 0x1ed90c0)
	/workspace/controllers/awscluster_controller.go:155 +0x158
sigs.k8s.io/cluster-api-provider-aws/controllers.(*AWSClusterReconciler).Reconcile(0xc0002bbb30, 0xc00069f120, 0xb, 0xc000683a80, 0x11, 0xc000589c00, 0x0, 0x1e6a320, 0xc0008e3880)
	/workspace/controllers/awscluster_controller.go:100 +0x659
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ce480, 0x19504c0, 0xc0006e0680, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ce480, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001ce480)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0005ec090)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005ec090, 0x3b9aca00, 0x0, 0x1, 0xc0000a8360)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc0005ec090, 0x3b9aca00, 0xc0000a8360)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191121015412-41065c7a8c2a/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328
```

**What did you expect to happen:**
No crash.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: master

/kind failing-test
/kind bug
/priority critical-urgent
/milestone v0.5.0
/assign

**Comment by ncdc** [comment]
Broken by https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1442

**Comment by vincepri** [comment]
@ncdc working on a fix or you want me to?

**Comment by ncdc** [comment]
I'm on it
