### ISSUE TITLE
Check for instance in clusterawsadm console output

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-aws#206]
/kind bug

**What steps did you take and what happened:**
Running  `clusterawsadm alpha ec2 console-output` against a machine not yet created in
EC2 panics:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1644b3c]

goroutine 1 [running]:                                                                                                                                                                            
sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/client.MachineInstanceID(0x7ffe61eb562c, 0x16, 0x0, 0xc000351380, 0x0, 0x0)                                                                
        /go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/client/client.go:81 +0x10c                                                                                     
sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/cmd/alpha/ec2.consoleOutputCmd.func1(0xc0005a1180, 0xc0005720a0, 0x1, 0x1)                                                                 
        /go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/cmd/alpha/ec2/ec2.go:54 +0xdc                                                                                  
sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra.(*Command).execute(0xc0005a1180, 0xc000572080, 0x1, 0x1, 0xc0005a1180, 0xc000572080)                                           
        /go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra/command.go:766 +0x2cc                                                                              
sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0005a0280, 0x1, 0xc0005a0280, 0xc0005a0500)                                                             
        /go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra/command.go:852 +0x2fd                                                                              
sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0005a0280, 0x16440a9, 0xc00057bf88)                                                                      
        /go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/github.com/spf13/cobra/command.go:800 +0x2b                                                                               
sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/cmd.Execute()
        /go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/cmd/root.go:42 +0x2b                                                                                           
main.main()
        /go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/clusterawsadm/main.go:19 +0x20     
```

**What did you expect to happen:**
Message that the ec2 instance doesn't exist

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
This was done in #199
