### ISSUE TITLE
Provider Pod panics after deploying a machinepool

### ISSUE THREAD

**Issue by erkules** [kubernetes-sigs/cluster-api-provider-aws#2741]
/kind bug

After deploying
[machinedeployment.txt](https://github.com/kubernetes-sigs/cluster-api-provider-aws/files/7124886/machinedeployment.txt)
I get a working cluster. So after creating the MachinePool/AWSManagedMachinePool the capa-controller-manager(Pod) terminates:

~~~
I0907 23:56:18.736879       1 cluster.go:496]  "msg"="reconciling encryption configuration"
I0907 23:56:18.736949       1 addons.go:34]  "msg"="Reconciling EKS addons"
I0907 23:56:18.805119       1 addons.go:105]  "msg"="no eks addons installed in cluster"  "cluster"="machinepool_capi-eks-machinepool-control-plane"
I0907 23:56:18.805150       1 addons.go:57]  "msg"="no addons installed and no addons to install, no action needed"
I0907 23:56:18.805168       1 identity_provider.go:32]  "msg"="reconciling oidc identity provider"
I0907 23:56:18.805192       1 cni.go:45]  "msg"="Reconciling aws-node DaemonSet in cluster"  "cluster-name"="capi-eks-machinepool" "cluster-namespace"="machinepool"
I0907 23:56:18.805209       1 reconcile.go:37]  "msg"="Reconciling aws-iam-authenticator configuration"  "cluster-name"="capi-eks-machinepool"
I0907 23:56:19.061209       1 reconcile.go:96]  "msg"="Reconciled aws-iam-authenticator configuration"  "cluster-name"="machinepool_capi-eks-machinepool-control-plane"
I0907 23:58:18.653376       1 nodegroup.go:548]  "msg"="EKS nodegroup is now available"  "nodegroup-name"="machinepool_capi-eks-machinepool-pool-0"
I0907 23:58:18.886026       1 deleg.go:130] awsmanagedmachinepool-resource "msg"="AWSManagedMachinePool setting defaults"  "name"="capi-eks-machinepool-pool-0"
I0907 23:58:18.891179       1 deleg.go:130] awsmanagedmachinepool-resource "msg"="AWSManagedMachinePool validate update"  "name"="capi-eks-machinepool-pool-0"
I0907 23:58:18.914588       1 deleg.go:130] awsmanagedmachinepool-resource "msg"="AWSManagedMachinePool setting defaults"  "name"="capi-eks-machinepool-pool-0"
I0907 23:58:18.916345       1 deleg.go:130] awsmanagedmachinepool-resource "msg"="AWSManagedMachinePool validate update"  "name"="capi-eks-machinepool-pool-0"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1f9f8f4]

goroutine 625 [running]:
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroupConfig(0xc0014c1260, 0xc0006a41e0, 0x0, 0x0)
        /workspace/pkg/cloud/services/eks/nodegroup.go:411 +0x574
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).reconcileNodegroup(0xc0014c1260, 0xc000806b40, 0xc0012d9860)
        /workspace/pkg/cloud/services/eks/nodegroup.go:473 +0x425
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/services/eks.(*NodegroupService).ReconcilePool(0xc0014c1260, 0xc0014c1260, 0xc00004a018)
        /workspace/pkg/cloud/services/eks/eks.go:107 +0x165
sigs.k8s.io/cluster-api-provider-aws/exp/controllers.(*AWSManagedMachinePoolReconciler).reconcileNormal(0xc0006c3720, 0x2b1aff8, 0xc00096dec0, 0xc0005dd580, 0xc0017a01c0, 0xc000819200, 0xc000806b40, 0xc000388840)
        /workspace/exp/controllers/awsmanagedmachinepool_controller.go:182 +0x1ba
sigs.k8s.io/cluster-api-provider-aws/exp/controllers.(*AWSManagedMachinePoolReconciler).Reconcile(0xc0006c3720, 0x2b1aff8, 0xc00096dec0, 0xc000b7f9c0, 0xb, 0xc000bfb680, 0x1b, 0xc00096de00, 0x0, 0x0, ...)
        /workspace/exp/controllers/awsmanagedmachinepool_controller.go:166 +0x7e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000968c80, 0x2b1af50, 0xc0003b5140, 0x241a7c0, 0xc0016b8860)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000968c80, 0x2b1af50, 0xc0003b5140, 0xc0006eca00)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc00069b9c0, 0xc000968c80, 0x2b1af50, 0xc0003b5140)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:210 +0x425
~~~

After deleting the MachinePool etc. I'm the controller Pod keeps up running.

**What did you expect to happen:**
I was hoping to have a running controler.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 0.7.0
- Kubernetes version: (use `kubectl version`): 
- Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
- OS (e.g. from `/etc/os-release`):  
Laptop or Host?

**Comment by richardcase** [comment]
I think this is fixed by #2713

**Comment by erkules** [comment]
So I need to wait for v0.7.1 thx

**Comment by richardcase** [comment]
@erkules - if this still an issue please re-open the issue.

After discussion in the refinement session:

/close
