### ISSUE TITLE
SEG fault in aws-provider-controller-manager

### ISSUE THREAD

**Issue by DheerajSShetty** [kubernetes-sigs/cluster-api-provider-aws#657]
/kind bug

**What steps did you take and what happened:**
kubectl create -f cmd/clusterctl/examples/aws/provider-components.yaml
kubectl create -f cmd/clusterctl/examples/aws/out/cluster.yaml

Create a controlplane using the yaml shown below
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: controlplane-0
  labels:
    cluster.k8s.io/cluster-name: test1
    set: controlplane
spec:
  versions:
    kubelet: v1.13.3
    controlPlane: v1.13.3
  providerSpec:
    value:
      apiVersion: awsprovider/v1alpha1
      kind: AWSMachineProviderSpec
      instanceType: "t2.medium"
      iamInstanceProfile: "control-plane.cluster-api-provider-aws.sigs.k8s.io"
      keyName: "default"

kubectl delete -f cmd/clusterctl/examples/aws/out/cluster.yaml

kubectl -n aws-provider-system logs -f aws-provider-controller-manager-0

GOROOT/src/runtime/panic.go:513
GOROOT/src/runtime/panic.go:82
GOROOT/src/runtime/signal_unix.go:390
pkg/cloud/aws/services/elb/loadbalancer.go:162
pkg/cloud/aws/services/elb/loadbalancer.go:88
pkg/cloud/aws/actuators/cluster/actuator.go:104
vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go:113
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215
vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib%/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf16293]

goroutine 140 [running]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x154a880, 0x281b890)
	GOROOT/src/runtime/panic.go:513 +0x1b9
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/elb.(*Service).getAPIServerClassicELBSpec(0xc00000c350, 0xc00048b988)
	pkg/cloud/aws/services/elb/loadbalancer.go:162 +0x353
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/services/elb.(*Service).DeleteLoadbalancers(0xc00000c350, 0xc00000c350, 0xc00048e640)
	pkg/cloud/aws/services/elb/loadbalancer.go:88 +0x84
sigs.k8s.io/cluster-api-provider-aws/pkg/cloud/aws/actuators/cluster.(*Actuator).Delete(0xc000534460, 0xc000161d40, 0x0, 0x0)
	pkg/cloud/aws/actuators/cluster/actuator.go:104 +0x23b
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster.(*ReconcileCluster).Reconcile(0xc00032ec00, 0xc000437550, 0x7, 0xc000437530, 0x5, 0x282ff00, 0xc00003ca80, 0xc000625d40, 0x4057bb)
	vendor/sigs.k8s.io/cluster-api/pkg/controller/cluster/controller.go:113 +0x6a9
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004d2320, 0x0)
	vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x18f
sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00027e0a0)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00027e0a0, 0x3b9aca00, 0x0, 0x1, 0xc00003c240)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00027e0a0, 0x3b9aca00, 0xc00003c240)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-aws/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x32a
**What did you expect to happen:**
Once we try deleting the cluster.yaml, aws-provider-controller-manager-0 should nt segfault

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by DheerajSShetty** [comment]
SImilar to the issue
https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/656. 
Hence closing this to avoid duplicate bugs.

**Comment by DheerajSShetty** [comment]
SImilar to the issue
#656.
Hence closing this to avoid duplicate bugs.
