### ISSUE TITLE
manager panics `no matches for kind "AWSMachine" in version "infrastructure.cluster.sigs.k8s.io/v1alpha2"`

### ISSUE THREAD

**Issue by tahsinrahman** [kubernetes-sigs/cluster-api-provider-aws#912]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```bash
$ make manager
go build -o bin/manager ./cmd/manager
$ ./bin/manager
I0720 00:29:46.653169   31666 listener.go:40] controller-runtime/metrics "level"=0 "msg"="metrics server is starting to listen"  "addr"=":8080"
I0720 00:29:46.654900   31666 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="cluster-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"providerSpec":{}},"status":{}}}
E0720 00:29:46.654982   31666 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Cluster\" in version \"cluster.sigs.k8s.io/v1alpha2\""  "kind"={"Group":"cluster.sigs.k8s.io","Kind":"Cluster"}
I0720 00:29:46.655398   31666 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="awsmachine-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"ami":{}},"status":{"ready":false}}}
E0720 00:29:46.655440   31666 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"AWSMachine\" in version \"infrastructure.cluster.sigs.k8s.io/v1alpha2\""  "kind"={"Group":"infrastructure.cluster.sigs.k8s.io","Kind":"AWSMachine"}
F0720 00:29:46.655457   31666 main.go:118] no matches for kind "AWSMachine" in version "infrastructure.cluster.sigs.k8s.io/v1alpha2"
goroutine 1 [running]:
k8s.io/klog.stacks(0x2ceb501, 0x3, 0xc00010e380, 0x85)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:900 +0xb1
k8s.io/klog.(*loggingT).output(0x2ceb5e0, 0xc000000003, 0xc00018eee0, 0x2c65d8d, 0x7, 0x76, 0x0)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:815 +0xe6
k8s.io/klog.(*loggingT).printDepth(0x2ceb5e0, 0xc000000003, 0x1, 0xc000647e00, 0x1, 0x1)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:718 +0x12b
k8s.io/klog.(*loggingT).print(...)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:709
k8s.io/klog.Fatal(...)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:1289
main.main()
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/manager/main.go:118 +0x87c

goroutine 34 [chan receive]:
k8s.io/klog.(*loggingT).flushDaemon(0x2ceb5e0)
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:1035 +0x8b
created by k8s.io/klog.init.0
	/home/tahsin/go/pkg/mod/k8s.io/klog@v0.3.2/klog.go:404 +0x6c

goroutine 28 [syscall]:
os/signal.signal_recv(0x45e576)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 205 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000248ba0)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/queue.go:198 +0xc2
created by k8s.io/client-go/util/workqueue.newQueue
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/queue.go:58 +0x133

goroutine 67 [IO wait]:
internal/poll.runtime_pollWait(0x7f881cd05070, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000574418, 0x72, 0x4400, 0x444b, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000574400, 0xc0002e2000, 0x444b, 0x444b, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000574400, 0xc0002e2000, 0x444b, 0x444b, 0x203000, 0x0, 0x443e)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010630, 0xc0002e2000, 0x444b, 0x444b, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00000ec60, 0xc0002e2000, 0x444b, 0x444b, 0x806, 0x1cf4340, 0xc0001019e0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00009b058, 0x1cf4180, 0xc00000ec60, 0x40b7a5, 0x17eab80, 0x19a8760)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00009ae00, 0x1cf5860, 0xc000010630, 0x5, 0xc000010630, 0x7e9)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00009ae00, 0x1aafc00, 0xc00009af38, 0xc000101d58)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00009ae00, 0xc000482000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc00013f620, 0xc000224498, 0x9, 0x9, 0x407e54, 0xc000340480, 0xc000101d58)
	/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1cf4000, 0xc00013f620, 0xc000224498, 0x9, 0x9, 0x9, 0x1cf4340, 0xc000149ae0, 0xc0000c2050)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
golang.org/x/net/http2.readFrameHeader(0xc000224498, 0x9, 0x9, 0x1cf4000, 0xc00013f620, 0x0, 0x0, 0x0, 0x0)
	/home/tahsin/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/frame.go:237 +0x88
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000224460, 0xc000141d40, 0x0, 0x0, 0x0)
	/home/tahsin/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/frame.go:492 +0xa1
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc000101fb8, 0x1aae6c0, 0xc000071fb8)
	/home/tahsin/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:1686 +0x8d
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0000a5500)
	/home/tahsin/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:1614 +0x76
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/tahsin/go/pkg/mod/golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980/http2/transport.go:673 +0x637

goroutine 196 [chan receive]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc000051d00)
	/home/tahsin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/watch/mux.go:207 +0x66
created by k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/tahsin/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190704094733-8f6ac2502e51/pkg/watch/mux.go:75 +0xcc

goroutine 231 [chan receive]:
k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc0002490e0)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/queue.go:198 +0xc2
created by k8s.io/client-go/util/workqueue.newQueue
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/queue.go:58 +0x133

goroutine 207 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000248d20)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/delaying_queue.go:209 +0x34b
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/delaying_queue.go:55 +0x1dd

goroutine 233 [select]:
k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000249260)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/delaying_queue.go:209 +0x34b
created by k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/util/workqueue/delaying_queue.go:55 +0x1dd

goroutine 197 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x1d06500, 0xc0002bc690, 0xc0002bc660)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/record/event.go:219 +0xa4
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/record/event.go:217 +0x6e

goroutine 133 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x1d06500, 0xc0005bc000, 0xc0001d91d0)
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/record/event.go:219 +0xa4
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/home/tahsin/go/pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/record/event.go:217 +0x6e
```

**What did you expect to happen:**

manager should not panic

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-aws version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vincepri** [comment]
Have you installed the CRDs in your target Kubernetes cluster from `config/crds`?

**Comment by tahsinrahman** [comment]
yes, i've applied the crds, but same error :( 

```console
$ kubectl apply -f config/crds/
customresourcedefinition.apiextensions.k8s.io/awsclusterproviderspecs.awsprovider.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsclusterproviderstatuses.awsprovider.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsmachineproviderspecs.awsprovider.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsmachineproviderstatuses.awsprovider.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsclusterproviderspecs.infrastructure.cluster.sigs.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsclusterproviderstatuses.infrastructure.cluster.sigs.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsmachines.infrastructure.cluster.sigs.k8s.io configured
customresourcedefinition.apiextensions.k8s.io/awsmachinetemplates.infrastructure.cluster.sigs.k8s.io configured
error: error validating "config/crds/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

$ make manager
go build -o bin/manager ./cmd/manager

$ ./bin/manager
I0720 23:09:41.392672   28597 listener.go:40] controller-runtime/metrics "level"=0 "msg"="metrics server is starting to listen"  "addr"=":8080"
I0720 23:09:41.394120   28597 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="cluster-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"providerSpec":{}},"status":{}}}
E0720 23:09:41.394177   28597 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Cluster\" in version \"cluster.sigs.k8s.io/v1alpha2\""  "kind"={"Group":"cluster.sigs.k8s.io","Kind":"Cluster"}
I0720 23:09:41.395393   28597 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="awsmachine-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"ami":{}},"status":{"ready":false}}}
I0720 23:09:41.395591   28597 controller.go:121] controller-runtime/controller "level"=0 "msg"="Starting EventSource"  "controller"="awsmachine-controller" "source"={"Type":{"metadata":{"creationTimestamp":null},"spec":{"metadata":{},"bootstrap":{},"infrastructureRef":{}},"status":{}}}
E0720 23:09:41.395625   28597 source.go:88] controller-runtime/source "msg"="if kind is a CRD, it should be installed before calling Start" "error"="no matches for kind \"Machine\" in version \"cluster.sigs.k8s.io/v1alpha2\""  "kind"={"Group":"cluster.sigs.k8s.io","Kind":"Machine"}
F0720 23:09:41.395635   28597 main.go:118] no matches for kind "Machine" in version "cluster.sigs.k8s.io/v1alpha2"
goroutine 1 [running]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.stacks(0x2eb2501, 0x3, 0xc00004a1a0, 0x73)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:900 +0xb1
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.(*loggingT).output(0x2eb25c0, 0xc000000003, 0xc0002b4540, 0x2e29e2a, 0x7, 0x76, 0x0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:815 +0xe6
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.(*loggingT).printDepth(0x2eb25c0, 0xc000000003, 0x1, 0xc0004ebe00, 0x1, 0x1)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:718 +0x12b
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.(*loggingT).print(...)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:709
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.Fatal(...)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:1289
main.main()
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/cmd/manager/main.go:118 +0x87c

goroutine 18 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.(*loggingT).flushDaemon(0x2eb25c0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:1035 +0x8b
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog.init.0
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/klog/klog.go:404 +0x6c

goroutine 24 [syscall]:
os/signal.signal_recv(0x45e576)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 54 [IO wait]:
internal/poll.runtime_pollWait(0x7f1c66608148, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000454418, 0x72, 0x3f00, 0x3f43, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000454400, 0xc00067a000, 0x3f43, 0x3f43, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000454400, 0xc00067a000, 0x3f43, 0x3f43, 0x203000, 0x0, 0x3f0c)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000106a8, 0xc00067a000, 0x3f43, 0x3f43, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00000e380, 0xc00067a000, 0x3f43, 0x3f43, 0xc00031fa08, 0x445ae2, 0xc00031f9e0)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc000199058, 0x1cf5260, 0xc00000e380, 0x40b7a5, 0x17eb2a0, 0x19a1d20)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc000198e00, 0x1cf56e0, 0xc0000106a8, 0x5, 0xc0000106a8, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc000198e00, 0x1ab1400, 0xc000198f38, 0xc00031fd58)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc000198e00, 0xc00044c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
bufio.(*Reader).Read(0xc0000a7860, 0xc000236498, 0x9, 0x9, 0x407e54, 0xc0006000c0, 0xc00031fd58)
	/usr/local/go/src/bufio/bufio.go:223 +0x23e
io.ReadAtLeast(0x1cf50e0, 0xc0000a7860, 0xc000236498, 0x9, 0x9, 0x9, 0x1cf5420, 0xc0001e4980, 0xc00003c070)
	/usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(...)
	/usr/local/go/src/io/io.go:329
sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2.readFrameHeader(0xc000236498, 0x9, 0x9, 0x1cf50e0, 0xc0000a7860, 0x0, 0x0, 0x0, 0x0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2/frame.go:237 +0x88
sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc000236460, 0xc0004b25a0, 0x0, 0x0, 0x0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2/frame.go:492 +0xa1
sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2.(*clientConnReadLoop).run(0xc00031ffb8, 0x1ab0af0, 0xc00006efb8)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2/transport.go:1686 +0x8d
sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2.(*ClientConn).readLoop(0xc000576f00)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2/transport.go:1614 +0x76
created by sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2.(*Transport).newClientConn
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/golang.org/x/net/http2/transport.go:673 +0x637

goroutine 216 [select]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc00037ac60)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:209 +0x34b
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:55 +0x1dd

goroutine 195 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x1d01600, 0xc000235aa0, 0xc000235a70)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record/event.go:219 +0xa4
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record/event.go:217 +0x6e

goroutine 194 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00047fd80)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 204 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc000601c20)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xc2
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.newQueue
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x133

goroutine 214 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc00037aae0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/queue.go:198 +0xc2
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.newQueue
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/queue.go:58 +0x133

goroutine 196 [chan receive]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x1d01600, 0xc000235ad0, 0xc0003885e0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record/event.go:219 +0xa4
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/tools/record/event.go:217 +0x6e

goroutine 206 [select]:
sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc000601da0)
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:209 +0x34b
created by sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
	/home/tahsin/go/src/sigs.k8s.io/cluster-api-provider-aws/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:55 +0x1dd
[I] ➜  cluster-api-provider-aws git:(master) 

```

**Comment by ncdc** [comment]
I am not able to reproduce this. I manually applied the following CRDs from github.com/kubernetes-sigs/cluster-api master:
- config/crds/cluster.x-k8s.io_clusters.yaml
- config/crds/cluster.x-k8s.io_machines.yaml

And from this repo, master:
- config/crds/infrastructure.cluster.x-k8s.io_awsmachines.yaml

Once I did that, the manager started.

**Comment by ncdc** [comment]
@tahsinrahman could you please try what I wrote above and report back? Thanks!

**Comment by tahsinrahman** [comment]
@ncdc thanks, it was panicing because i didn't apply the yamls from `cluster-api`
